[package]
name = "explore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.98"
bytesize = "2.0.1"
clap = { version = "4.5.37", features = ["derive"] }
colored = "3.0.0"
jiff = { version = "0.2.11", features = ["alloc"] }
walkdir = "2.5.0"
